name: Code Linter

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install PolUVR[cpu] flake8 pylint vulture

      - name: Run flake8
        run: flake8 .
        continue-on-error: true

      - name: Run PyLint
        run: pylint .
        continue-on-error: true

      - name: Run Vulture
        run: vulture .
        continue-on-error: true
